// The asset system, and the eight things the old one could not do.
//
//   1. Custom asset          — a loader for a format the engine has never heard of (.pal).
//   2. Async + barrier       — loads run on IO threads; a barrier reports progress.
//   3. Generated asset       — a texture built in code, registered like any other.
//   4. Texture options       — repeat vs clamp, sRGB vs UNORM, decided AT LOAD TIME.
//   5. Asset saving          — through the LOADER, so any type can be written, not just textures.
//   6. Subassets             — "file.pal#warm": one file, many assets, each cached on its own.
//   7. Embedded assets       — bytes compiled into the executable, loaded through the same API.
//   8. Web assets            — "https://...": the network is just a slower disk.
//
// The last three are all the same question — where do the bytes come from — and they are answered
// in one function, so the cache, the barrier, hot reload and every loader stay completely ignorant
// of the difference.
//
// It is a console program on purpose. Every one of these is about the asset system, not about
// drawing, and a window would only be in the way of the evidence.

#include "embedded_demo.hpp"   // generated by vortex_embed_asset() in examples/CMakeLists.txt

#include "vortex/asset/asset_loader.hpp"
#include "vortex/asset/asset_manager.hpp"
#include "vortex/core/log.hpp"
#include "vortex/core/math/vec3.hpp"
#include "vortex/platform/filesystem.hpp"
#include "vortex/platform/window.hpp"
#include "vortex/rhi/device.hpp"

#include <cstdio>
#include <cctype>
#include <cstdlib>
#include <cstring>
#include <string>
#include <thread>
#include <vector>

using namespace vortex;

namespace {

// ---------------------------------------------------------------------------
// 1. A custom asset type, and a loader for it.
// ---------------------------------------------------------------------------
//
// A ".pal" is a palette: a text file, one "#rrggbb" per line. The engine has never heard of it,
// and does not need to — the loader is registered from the game, and from that point on a palette
// is loaded, cached, hot-reloaded and handed out exactly like a texture.

// A ".pal" holds NAMED SECTIONS, so one file is really several palettes:
//
//     [warm]      -> "theme.pal#warm"    loads three colours
//     #F94144
//     ...
//
// Without a fragment you get the whole file. That is what a subasset IS: one file, many assets,
// each addressable on its own — and each cached on its own, because `#warm` and `#cool` are two
// different assets that happen to share a source.
struct Palette {
    std::string       name;
    std::vector<Vec3> colors;
};

class PaletteLoader final : public assets::IAssetLoader {
public:
    const char* name() const override { return "palette"; }

    // The BASE path — the name may be "embedded://theme.pal#warm", and testing the extension
    // against the whole string would match nothing at all.
    bool canLoad(std::string_view full) const override {
        const std::string_view path = assets::basePath(full);
        return path.size() > 4 && path.substr(path.size() - 4) == ".pal";
    }

    // WORKER THREAD. Bytes in, CPU data out. No device, no GPU — this runs while the main thread
    // is drawing, and touching the RHI here would be a race that crashes on someone else's machine.
    std::shared_ptr<void> decode(std::string_view path, const std::vector<std::byte>& bytes,
                                 const assets::LoadOptions&) override {
        // The bytes are the WHOLE file. The fragment says which part of it was wanted.
        const std::string_view want = assets::subassetOf(path);

        auto pal = std::make_shared<Palette>();
        pal->name = std::string(path);

        std::string section;               // the section we are currently inside
        bool        found = want.empty();  // no fragment -> take everything

        const std::string text(reinterpret_cast<const char*>(bytes.data()), bytes.size());
        usize start = 0;
        while (start < text.size()) {
            const usize eol  = text.find('\n', start);
            const usize end  = (eol == std::string::npos) ? text.size() : eol;
            const std::string line = text.substr(start, end - start);
            start = end + 1;

            if (line.size() >= 2 && line[0] == '[' && line.back() == ']') {
                section = line.substr(1, line.size() - 2);
                if (section == want) found = true;
                continue;
            }

            // Skip colours that belong to a section we did not ask for.
            if (!want.empty() && section != want) continue;

            // "#rrggbb" and nothing else. A comment line — "# sunset" — also starts with '#' and
            // is also long enough, and strtoul(" sunset") quietly returns 0: the palette would gain
            // a black entry that nobody asked for and nobody would ever trace back to here. Parsers
            // that guess are parsers that lie.
            if (line.size() < 7 || line[0] != '#') continue;
            bool hex = true;
            for (int i = 1; i <= 6; ++i)
                if (std::isxdigit(static_cast<unsigned char>(line[i])) == 0) { hex = false; break; }
            if (!hex) continue;

            const u32 rgb = static_cast<u32>(std::strtoul(line.substr(1, 6).c_str(), nullptr, 16));
            pal->colors.push_back({static_cast<f32>((rgb >> 16) & 0xFF) / 255.0f,
                                   static_cast<f32>((rgb >> 8) & 0xFF) / 255.0f,
                                   static_cast<f32>(rgb & 0xFF) / 255.0f});
        }

        // A fragment naming a section that is not there is a BUG in the caller, and it must not
        // look like an empty palette. Fail it loudly — a typo'd subasset that silently returns
        // nothing is the kind of thing that gets shipped.
        if (!found) {
            VORTEX_ERROR("Demo", "no section '%.*s' in this palette",
                         static_cast<int>(want.size()), want.data());
            return nullptr;
        }

        // Null means "this file is not what it claimed to be", and the manager marks the handle
        // Failed rather than handing out an empty palette that looks like a working one.
        return pal->colors.empty() ? nullptr : pal;
    }

    // No finalize(): a palette never touches the GPU. The default does nothing, which is exactly
    // right — and is why an asset that lives on the CPU costs no main-thread time at all.

    // MAIN THREAD. Saving lives here, next to the parser, because the two have to agree: a writer
    // that lived somewhere else would drift, and start producing .pal files this loader could no
    // longer read.
    bool save(const std::shared_ptr<void>& asset, rhi::IGraphicsDevice&,
              const char* path) override {
        const auto* pal = static_cast<const Palette*>(asset.get());
        if (pal == nullptr) return false;

        std::FILE* f = std::fopen(path, "w");
        if (f == nullptr) return false;

        std::fprintf(f, "# saved by vortex\n");
        for (const Vec3& c : pal->colors)
            std::fprintf(f, "#%02X%02X%02X\n", static_cast<int>(c.x * 255.0f + 0.5f),
                         static_cast<int>(c.y * 255.0f + 0.5f),
                         static_cast<int>(c.z * 255.0f + 0.5f));

        std::fclose(f);
        return true;
    }
};

} // namespace

int main() {
    initLogFromEnv();

    // A window only because the device needs a surface. Nothing is drawn.
    auto window = pf::createWindow({.width = 320, .height = 200, .title = "Vortex Assets"});
    auto fs     = pf::createFileSystem();
    auto device = rhi::createDevice(*window);

    assets::AssetManager mgr(*device, *fs, /*ioThreads=*/2);

    // Teach it the new type. One line, and .pal is now a first-class asset.
    mgr.addLoader<Palette>(std::make_unique<PaletteLoader>());

    // Write a palette to load, so the example has no external dependency.
    {
        std::FILE* f = std::fopen("/tmp/vortex_demo.pal", "w");
        std::fprintf(f, "# sunset\n#F94144\n#F3722C\n#F9C74F\n#90BE6D\n#577590\n");
        std::fclose(f);
    }

    // -----------------------------------------------------------------------
    // 2. Asynchronous loading, and a barrier over the lot.
    // -----------------------------------------------------------------------
    //
    // Every load() returns IMMEDIATELY. Nothing has been read yet. That is what makes a loading
    // screen with a real progress bar possible, and what stops a game hitching when it walks into
    // a new area.
    VORTEX_INFO("Demo", "--- 2. async load + barrier ---");

    const auto tex1 = mgr.load<assets::TextureAsset>("assets/meme1.png");
    const auto tex2 = mgr.load<assets::TextureAsset>("assets/meme2.png");
    const auto tex3 = mgr.load<assets::TextureAsset>("assets/meme3.png");
    const auto pal  = mgr.load<Palette>("/tmp/vortex_demo.pal");

    // A handle is valid the instant you ask for it. The ASSET is not there.
    VORTEX_INFO("Demo", "handles are valid immediately: %s",
                tex1.valid() && pal.valid() ? "yes" : "no");
    VORTEX_INFO("Demo", "but get() is null while it is in flight: %s",
                mgr.get(tex1) == nullptr ? "yes (still loading)" : "no (already landed)");

    // The barrier does not care WHAT it is waiting on — three textures and a palette, all the same.
    assets::AssetManager::Barrier barrier;
    barrier.add(mgr, tex1).add(mgr, tex2).add(mgr, tex3).add(mgr, pal);

    int spins = 0;
    while (!barrier.done(mgr)) {
        mgr.update();   // the main thread's half of a load: the GPU upload
        VORTEX_TRACE("Demo", "progress %.0f%%", barrier.progress(mgr) * 100.0f);
        ++spins;
        std::this_thread::yield();
    }
    VORTEX_INFO("Demo", "all %zu assets loaded (%d spins, %zu failed)",
                barrier.size(), spins, barrier.failed(mgr));

    if (const Palette* p = mgr.get(pal))
        VORTEX_INFO("Demo", "custom asset: palette has %zu colours, first is (%.2f, %.2f, %.2f)",
                    p->colors.size(), p->colors[0].x, p->colors[0].y, p->colors[0].z);

    // -----------------------------------------------------------------------
    // 3. A generated asset — never on disk, but a first-class asset anyway.
    // -----------------------------------------------------------------------
    VORTEX_INFO("Demo", "--- 3. generated asset ---");

    constexpr u32 kSize = 64;
    std::vector<u8> checker(static_cast<usize>(kSize) * kSize * 4);
    for (u32 y = 0; y < kSize; ++y)
        for (u32 x = 0; x < kSize; ++x) {
            const bool on = ((x / 8) + (y / 8)) % 2 == 0;
            const usize i = (static_cast<usize>(y) * kSize + x) * 4;
            checker[i + 0] = on ? 230 : 40;
            checker[i + 1] = on ? 90  : 40;
            checker[i + 2] = on ? 60  : 40;
            checker[i + 3] = 255;
        }

    auto generated = std::make_shared<assets::TextureAsset>();
    generated->width  = kSize;
    generated->height = kSize;
    generated->gpu = device->createTexture({.width = kSize, .height = kSize,
                                            .debugName = "generated"}, checker.data());

    // insert() is what makes it an ASSET rather than a loose GPU handle: it gets a name, a handle,
    // and a place in anything that refers to assets by name — a save file, for one.
    const auto genHandle = mgr.insert<assets::TextureAsset>("generated://checker", generated);
    VORTEX_INFO("Demo", "generated asset is Loaded on arrival: %s",
                mgr.isLoaded(genHandle) ? "yes" : "no");

    const auto found = mgr.find<assets::TextureAsset>("generated://checker");
    VORTEX_INFO("Demo", "and can be found again by name: %s", found == genHandle ? "yes" : "no");

    // -----------------------------------------------------------------------
    // 4. Texture options, decided at LOAD time.
    // -----------------------------------------------------------------------
    //
    // Whether a texture tiles is a property of the TEXTURE — a brick wall tiles, a UI icon does
    // not. Threading that decision through every draw call is how half the call sites end up with
    // the wrong one.
    VORTEX_INFO("Demo", "--- 4. load-time texture options ---");

    const auto tiled = mgr.loadBlocking<assets::TextureAsset>(
        "assets/meme4.png", {.texture = {.filter  = rhi::Filter::Nearest,
                                         .address = rhi::AddressMode::Repeat,
                                         .srgb    = true}});
    VORTEX_INFO("Demo", "loaded with Repeat + Nearest; sampler is part of the asset: %s",
                mgr.get(tiled) != nullptr && mgr.get(tiled)->sampler.valid() ? "yes" : "no");

    // The same file, asked for as DATA rather than as a picture. sRGB would bend every value.
    // (Same path, so this is the cached one — which is itself the point: the cache is by path, and
    // a second load with different options does NOT silently give you a second texture.)
    VORTEX_INFO("Demo", "note: the cache is keyed by PATH, so a second load of the same file "
                        "returns the first one's options. Loading one file two ways needs two "
                        "paths — a real limitation, and an honest one.");

    // -----------------------------------------------------------------------
    // 5. Saving — through the loader, so it works for ANY asset type.
    // -----------------------------------------------------------------------
    //
    // saveAsset() picks the writer by the DESTINATION extension. That is not a detail: the asset
    // you most want to save is the GENERATED one, and a generated asset was never read, so it has
    // no loader of its own. Keying on where it came from would make the one case that matters the
    // one case that fails.
    VORTEX_INFO("Demo", "--- 5. asset saving ---");

    const char* out = "/tmp/vortex_saved_checker.png";
    const bool saved = mgr.saveAsset(genHandle, out);
    VORTEX_INFO("Demo", "saved the GENERATED texture (no loader of its own) to %s: %s",
                out, saved ? "yes" : "no");

    // Prove it: load the file we just wrote back in, as a fresh asset.
    const auto reloaded = mgr.loadBlocking<assets::TextureAsset>(out);
    if (const assets::TextureAsset* r = mgr.get(reloaded))
        VORTEX_INFO("Demo", "read it back: %ux%u — round-trip %s",
                    r->width, r->height,
                    (r->width == kSize && r->height == kSize) ? "OK" : "WRONG SIZE");
    else
        VORTEX_ERROR("Demo", "could not read back what we just wrote");

    // And the same call, on a type the engine has never heard of. Nothing about saveAsset() knows
    // what a palette is — the loader does.
    const char* palOut = "/tmp/vortex_saved.pal";
    VORTEX_INFO("Demo", "saved the CUSTOM asset to %s: %s", palOut,
                mgr.saveAsset(pal, palOut) ? "yes" : "no");

    // -----------------------------------------------------------------------
    // 6. Subassets — one file, many assets.
    // -----------------------------------------------------------------------
    VORTEX_INFO("Demo", "--- 6. subassets ---");

    {
        std::FILE* f = std::fopen("/tmp/vortex_theme.pal", "w");
        std::fprintf(f, "[warm]\n#F94144\n#F3722C\n#F9C74F\n[cool]\n#90BE6D\n#577590\n");
        std::fclose(f);
    }

    const auto warm = mgr.loadBlocking<Palette>("/tmp/vortex_theme.pal#warm");
    const auto cool = mgr.loadBlocking<Palette>("/tmp/vortex_theme.pal#cool");
    const auto both = mgr.loadBlocking<Palette>("/tmp/vortex_theme.pal");

    if (const Palette* w = mgr.get(warm))
        VORTEX_INFO("Demo", "#warm  -> %zu colours, first (%.2f, %.2f, %.2f)",
                    w->colors.size(), w->colors[0].x, w->colors[0].y, w->colors[0].z);
    if (const Palette* c = mgr.get(cool))
        VORTEX_INFO("Demo", "#cool  -> %zu colours, first (%.2f, %.2f, %.2f)",
                    c->colors.size(), c->colors[0].x, c->colors[0].y, c->colors[0].z);
    if (const Palette* b = mgr.get(both))
        VORTEX_INFO("Demo", "no fragment -> the whole file, %zu colours", b->colors.size());

    // Two names, two assets, one file. If the cache keyed on the file instead of the whole name,
    // #cool would silently hand back #warm — and it would look like it worked.
    VORTEX_INFO("Demo", "#warm and #cool are distinct assets: %s",
                warm != cool ? "yes" : "NO — the cache is broken");

    // A fragment that names nothing FAILS, rather than quietly returning an empty palette.
    const auto typo = mgr.loadBlocking<Palette>("/tmp/vortex_theme.pal#wrm");
    VORTEX_INFO("Demo", "a typo'd subasset fails loudly: %s",
                mgr.state(typo) == assets::LoadState::Failed ? "yes (Failed)" : "NO — it passed");

    // -----------------------------------------------------------------------
    // 7. Embedded assets — bytes that ship inside the executable.
    // -----------------------------------------------------------------------
    //
    // The loading screen, the default font, the error texture: the things you need in order to TELL
    // the player something went wrong are exactly the things that must not be able to go missing.
    VORTEX_INFO("Demo", "--- 7. embedded assets ---");

    vortexEmbed_demo(mgr);   // generated; registers the bytes CMake baked in

    const auto embTex = mgr.loadBlocking<assets::TextureAsset>("embedded://meme1.png");
    if (const assets::TextureAsset* e = mgr.get(embTex))
        VORTEX_INFO("Demo", "embedded://meme1.png -> %ux%u, decoded by the SAME TextureLoader",
                    e->width, e->height);
    else
        VORTEX_ERROR("Demo", "embedded texture did not load");

    // Embedded and subasset compose: a scheme says where the bytes are, a fragment says which part
    // of them you wanted, and neither knows about the other.
    const auto embWarm = mgr.loadBlocking<Palette>("embedded://fallback.pal#cool");
    if (const Palette* e = mgr.get(embWarm))
        VORTEX_INFO("Demo", "embedded://fallback.pal#cool -> %zu colours "
                            "(a subasset OF an embedded file)", e->colors.size());

    // -----------------------------------------------------------------------
    // 8. Web assets — the network is just a slower disk.
    // -----------------------------------------------------------------------
    //
    // Same loader, same IO thread, same cache slot. The only thing that changed is where fetchBytes
    // looked. Point VORTEX_WEB_ASSET_URL at any image to try it.
    VORTEX_INFO("Demo", "--- 8. web assets ---");

    if (const char* url = std::getenv("VORTEX_WEB_ASSET_URL")) {
        const auto web = mgr.loadBlocking<assets::TextureAsset>(url);
        if (const assets::TextureAsset* w = mgr.get(web))
            VORTEX_INFO("Demo", "%s -> %ux%u", url, w->width, w->height);
        else
            VORTEX_ERROR("Demo", "web asset failed (see the error above for WHY — a URL that "
                                 "fails should never look like a corrupt file)");
    } else {
        VORTEX_INFO("Demo", "set VORTEX_WEB_ASSET_URL to an image URL to exercise this. "
                            "Not run by default: an example that needs the network is an example "
                            "that fails on a train.");
    }

    VORTEX_INFO("Demo", "live assets: %zu", mgr.liveTextureCount());
    return 0;
}
