# Build-time generator: turns a list of files into a C++ source with the bytes in it.
#
# Run via `cmake -P`, never included. vortex_embed_asset() in VortexEmbed.cmake is the front door.
#
# Inputs: OUT, HDR, SUFFIX, FILES (;-list of absolute paths), NAMES (;-list of asset names).

list(LENGTH FILES file_count)
list(LENGTH NAMES name_count)
if(NOT file_count EQUAL name_count)
    message(FATAL_ERROR "EmbedAssets: ${file_count} files but ${name_count} names")
endif()

set(arrays "")
set(calls  "")
math(EXPR last "${file_count} - 1")

# Sixteen "0x..," groups, spelled out.
#
# Not written as "(0x..,){16}" because CMake's regex engine has NO BOUNDED REPETITION: it does not
# error on {16}, it simply matches nothing. The first version of this file used it, emitted one
# 37,754-character line, and looked like it worked. Built once, outside the loop — string(APPEND)
# inside it would accumulate, and the second file would be wrapped every 32 bytes instead of 16.
set(chunk16 "")
foreach(n RANGE 1 16)
    string(APPEND chunk16 "0x..,")
endforeach()

foreach(i RANGE ${last})
    list(GET FILES ${i} path)
    list(GET NAMES ${i} name)

    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "EmbedAssets: no such file: ${path}")
    endif()

    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")

    if(byte_count EQUAL 0)
        message(FATAL_ERROR "EmbedAssets: ${path} is empty")
    endif()

    # "0a1b2c" -> "0x0a,0x1b,0x2c,".
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")

    # A newline every 16 bytes, because a single multi-megabyte line makes every text editor that
    # ever opens this file unusable — and someone will open it.
    string(REGEX REPLACE "(${chunk16})" "\\1\n    " bytes "${bytes}")

    string(APPEND arrays
        "// ${name} (${byte_count} bytes)\n"
        "alignas(16) const unsigned char kData${i}[] = {\n    ${bytes}\n};\n\n")

    string(APPEND calls
        "    mgr.embed(\"${name}\",\n"
        "              {reinterpret_cast<const std::byte*>(kData${i}), sizeof(kData${i})});\n")

    message(STATUS "embedding ${name} (${byte_count} bytes)")
endforeach()

file(WRITE "${HDR}"
"// Generated by vortex_embed_asset(). Do not edit.
#pragma once
namespace vortex::assets { class AssetManager; }

// Registers every embedded asset. Call once, before the first load.
void vortexEmbed_${SUFFIX}(vortex::assets::AssetManager& mgr);
")

get_filename_component(hdr_name "${HDR}" NAME)

file(WRITE "${OUT}"
"// Generated by vortex_embed_asset(). Do not edit.
//
// The bytes below live in the executable's read-only data. That is the entire point: a shipped
// game is one file, and the assets it needs in order to say \"something went wrong\" cannot
// themselves be the thing that went missing.

#include \"${hdr_name}\"
#include \"vortex/asset/asset_manager.hpp\"

#include <cstddef>

namespace {

${arrays}}

void vortexEmbed_${SUFFIX}(vortex::assets::AssetManager& mgr) {
${calls}}
")
